from enum import IntEnum


class InstructionSet(IntEnum):

    MOTOR_START_SEND = 110
    MOTOR_START_ACK = 111
    MOTOR_START_CONFIRMED = 112

    MOTOR_SLOW_SEND = 120
    MOTOR_SLOW_ACK = 121
    MOTOR_SLOW_CONFIRMED = 122

    MOTOR_FAST_SEND = 130
    MOTOR_FAST_ACK = 131
    MOTOR_FAST_CONFIRMED = 132

    MOTOR_SET_SPEED_SEND = 140
    MOTOR_SET_SPEED_ACK = 141
    MOTOR_SET_SPEED_CONFIRMED = 142

    MOTOR_STOP_SEND = 190
    MOTOR_STOP_ACK = 191
    MOTOR_STOP_CONFIRMED = 192

    SENSOR_START_SEND = 510
    SENSOR_START_ACK = 511
    SENSOR_START_CONFIRMED = 512

    SENSOR_CALIBRATE_SEND = 520
    SENSOR_CALIBRATE_ACK = 521
    SENSOR_CALIBRATE_CONFIRMED = 522

    SENSOR_STOP_SEND = 590
    SENSOR_STOP_ACK = 591
    SENSOR_STOP_CONFIRMED = 592

    TOF_START = 410
    TOF_STOP = 490

    CRANE_START_SEND = 210
    CRANE_START_ACK = 211
    CRANE_START_CONFIRMED = 212

    CRANE_STOP_SEND = 290
    CRANE_STOP_ACK = 291
    CRANE_STOP_CONFIRMED = 292

    LOAD_START_SEND = 710
    LOAD_START_ACK = 711
    LOAD_START_CONFIRMED = 712

    LOAD_NO_SENSOR_START_SEND = 720
    LOAD_NO_SENSOR_START_ACK = 721
    LOAD_NO_SENSOR_START_CONFIRMED = 722

    HANDSHAKE_SYN_SEND = 900
    HANDSHAKE_SYN_ACK = 901
    HANDSHAKE_SYN_CONFIRMED = 902

    CALL_SENSOR_DATA_SEND = 990
    CALL_SENSOR_DATA_ACK = 991
    CALL_SENSOR_DATA_CONFIRMED = 992




